skip_commits:
  files:
    - '**/*.md'

install:
  - cinst pester
  - ps: Install-Module SqlServer -AllowClobber -Force
  - ps: Install-Module OMSIngestionAPI -Force

build: off

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -Path .\tests -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }