skip_commits:
  files:
    - '**/*.md'

install:
  - choco install pester --version=4.10.1
  - ps: Install-Module 'Az.Accounts' -MinimumVersion '2.13.1' -AllowClobber -Force
  - ps: Install-Module SqlServer -MinimumVersion '22.1.1' -AllowClobber -Force
  - ps: Install-Module OMSIngestionAPI -Force
  - ps: Import-Module SqlServer -Version 22.1.1

build: off

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -Path .\tests -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
