. $PSScriptRoot/Test-TraceFlags.ps1
. $PSScriptRoot/Get-NumberOfErrorLogs.ps1
. $PSScriptRoot/Get-TLogsWithLargeGrowthSize.ps1
. $PSScriptRoot/Get-DatabasesWithoutDDLTrigger.ps1
. $PSScriptRoot/Get-OversizedIndexes.ps1
. $PSScriptRoot/Get-TLogWithPercentageGrowth.ps1
. $PSScriptRoot/Get-DatabasesOverMaxDataFileSpaceUsed.ps1
. $PSScriptRoot/Get-DbsWithoutGoodCheckDb.ps1
. $PSScriptRoot/Get-DuplicateIndexes.ps1
. $PSScriptRoot/Get-DbsWithoutAutogrow.ps1
