. $PSScriptRoot/Test-TraceFlags.ps1
. $PSScriptRoot/Get-NumberOfErrorLogs.ps1
. $PSScriptRoot/Get-TLogsWithLargeGrowthSize.ps1
. $PSScriptRoot/Get-DatabaseTriggerStatus.ps1
. $PSScriptRoot/Get-OversizedIndexes.ps1
. $PSScriptRoot/Get-TLogWithPercentageGrowth.ps1
. $PSScriptRoot/Get-DatabaseFilesOverMaxDataFileSpaceUsed.ps1
. $PSScriptRoot/Get-DbsWithoutGoodCheckDb.ps1
. $PSScriptRoot/Get-DuplicateIndexes.ps1
. $PSScriptRoot/Get-FixedSizeFiles.ps1
. $PSScriptRoot/Get-AutoGrowthRisks.ps1
. $PSScriptRoot/Get-DatabasesToCheck.ps1